---
name: Digest-MD5-Reverse
version: 1.3
author:
  - 'Urma Raoul-Gabriel <blwood@skynet.be>'
abstract: MD5 Reverse Lookup
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
provides:
  Digest::MD5::Reverse:
    file: lib/Digest/MD5/Reverse.pm
    version: 1.3
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
